//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.21 at 08:47:29 PM CDT 
//
package mx.com.api.cfdi;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cfdiRelacionados",
    "emisor",
    "receptor",
    "conceptos",
    "impuestos",
    "complemento",
    "addenda"
})
@XmlRootElement(name = "Comprobante")
public class Comprobante {

    @XmlElement(name = "CfdiRelacionados")
    protected CfdiRelacionados cfdiRelacionados;
    @XmlElement(name = "Emisor", required = true)
    protected Emisor emisor;
    @XmlElement(name = "Receptor", required = true)
    protected Receptor receptor;
    @XmlElement(name = "Conceptos", required = true)
    protected Conceptos conceptos;
    @XmlElement(name = "Impuestos")
    protected ResumenImpuestos impuestos;
    @XmlElement(name = "Complemento")
    protected Complemento complemento;
    @XmlElement(name = "Addenda")
    protected Addenda addenda;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "Serie")
    protected String serie;
    @XmlAttribute(name = "Folio")
    protected String folio;
    @XmlAttribute(name = "Fecha", required = true)
    protected XMLGregorianCalendar fecha;
    @XmlAttribute(name = "Sello", required = true)
    protected String sello;
    @XmlAttribute(name = "FormaPago")
    protected String formaPago;
    @XmlAttribute(name = "NoCertificado", required = true)
    protected String noCertificado;
    @XmlAttribute(name = "Certificado", required = true)
    protected String certificado;
    @XmlAttribute(name = "CondicionesDePago")
    protected String condicionesDePago;
    @XmlAttribute(name = "SubTotal", required = true)
    protected BigDecimal subTotal;
    @XmlAttribute(name = "Descuento")
    protected BigDecimal descuento;
    @XmlAttribute(name = "Moneda", required = true)
    protected String moneda;
    @XmlAttribute(name = "TipoCambio")
    protected BigDecimal tipoCambio;
    @XmlAttribute(name = "Total", required = true)
    protected BigDecimal total;
    @XmlAttribute(name = "TipoDeComprobante", required = true)
    protected String tipoComprobante;
    @XmlAttribute(name = "MetodoPago")
    protected String metodoPago;
    @XmlAttribute(name = "LugarExpedicion", required = true)
    protected String lugarExpedicion;
    @XmlAttribute(name = "Confirmacion")
    protected String confirmacion;

    public Comprobante() {
        this.impuestos = new ResumenImpuestos();
        this.conceptos = new Conceptos();
        this.complemento = new Complemento();
    }
    
    
    /**
     * Gets the value of the cfdiRelacionados property.
     *
     * @return possible object is {@link Comprobante.CfdiRelacionados }
     *
     */
    public CfdiRelacionados getCfdiRelacionados() {
        return cfdiRelacionados;
    }

    /**
     * Sets the value of the cfdiRelacionados property.
     *
     * @param value allowed object is {@link Comprobante.CfdiRelacionados }
     *
     */
    public void setCfdiRelacionados(CfdiRelacionados value) {
        this.cfdiRelacionados = value;
    }

    /**
     * Gets the value of the emisor property.
     *
     * @return possible object is {@link Comprobante.Emisor }
     *
     */
    public Emisor getEmisor() {
        return emisor;
    }

    /**
     * Sets the value of the emisor property.
     *
     * @param value allowed object is {@link Comprobante.Emisor }
     *
     */
    public void setEmisor(Emisor value) {
        this.emisor = value;
    }

    /**
     * Gets the value of the receptor property.
     *
     * @return possible object is {@link Comprobante.Receptor }
     *
     */
    public Receptor getReceptor() {
        return receptor;
    }

    /**
     * Sets the value of the receptor property.
     *
     * @param value allowed object is {@link Comprobante.Receptor }
     *
     */
    public void setReceptor(Receptor value) {
        this.receptor = value;
    }

    /**
     * Gets the value of the conceptos property.
     *
     * @return possible object is {@link Comprobante.Conceptos }
     *
     */
    public Conceptos getConceptos() {
        return conceptos;
    }

    /**
     * Sets the value of the conceptos property.
     *
     * @param value allowed object is {@link Comprobante.Conceptos }
     *
     */
    public void setConceptos(Conceptos value) {
        this.conceptos = value;
    }

    /**
     * Gets the value of the impuestos property.
     *
     * @return possible object is {@link Comprobante.Impuestos }
     *
     */
    public ResumenImpuestos getImpuestos() {
        return impuestos;
    }

    /**
     * Sets the value of the impuestos property.
     *
     * @param value allowed object is {@link Comprobante.Impuestos }
     *
     */
    public void setImpuestos(ResumenImpuestos value) {
        this.impuestos = value;
    }

    public Complemento getComplemento() {
        return complemento;
    }

    public void setComplemento(Complemento complemento) {
        this.complemento = complemento;
    }

    /**
     * Gets the value of the addenda property.
     *
     * @return possible object is {@link Comprobante.Addenda }
     *
     */
    public Addenda getAddenda() {
        return addenda;
    }

    /**
     * Sets the value of the addenda property.
     *
     * @param value allowed object is {@link Comprobante.Addenda }
     *
     */
    public void setAddenda(Addenda value) {
        this.addenda = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getVersion() {
        if (version == null) {
            return "3.3";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the serie property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSerie() {
        return serie;
    }

    /**
     * Sets the value of the serie property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSerie(String value) {
        this.serie = value;
    }

    /**
     * Gets the value of the folio property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFolio() {
        return folio;
    }

    /**
     * Sets the value of the folio property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFolio(String value) {
        this.folio = value;
    }

    /**
     * Gets the value of the fecha property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFecha() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setFecha(XMLGregorianCalendar value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the sello property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSello() {
        return sello;
    }

    /**
     * Sets the value of the sello property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSello(String value) {
        this.sello = value;
    }

    /**
     * Gets the value of the formaPago property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFormaPago() {
        return formaPago;
    }

    /**
     * Sets the value of the formaPago property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFormaPago(String value) {
        this.formaPago = value;
    }

    /**
     * Gets the value of the noCertificado property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNoCertificado() {
        return noCertificado;
    }

    /**
     * Sets the value of the noCertificado property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNoCertificado(String value) {
        this.noCertificado = value;
    }

    /**
     * Gets the value of the certificado property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCertificado() {
        return certificado;
    }

    /**
     * Sets the value of the certificado property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCertificado(String value) {
        this.certificado = value;
    }

    /**
     * Gets the value of the condicionesDePago property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCondicionesDePago() {
        return condicionesDePago;
    }

    /**
     * Sets the value of the condicionesDePago property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCondicionesDePago(String value) {
        this.condicionesDePago = value;
    }

    /**
     * Gets the value of the subTotal property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getSubTotal() {
        return subTotal;
    }

    /**
     * Sets the value of the subTotal property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setSubTotal(BigDecimal value) {
        this.subTotal = value;
    }

    /**
     * Gets the value of the descuento property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getDescuento() {
        return descuento;
    }

    /**
     * Sets the value of the descuento property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setDescuento(BigDecimal value) {
        this.descuento = value;
    }

    /**
     * Gets the value of the moneda property.
     *
     * @return possible object is {@link CMoneda }
     *
     */
    public String getMoneda() {
        return moneda;
    }

    /**
     * Sets the value of the moneda property.
     *
     * @param value allowed object is {@link CMoneda }
     *
     */
    public void setMoneda(String value) {
        this.moneda = value;
    }

    /**
     * Gets the value of the tipoCambio property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getTipoCambio() {
        return tipoCambio;
    }

    /**
     * Sets the value of the tipoCambio property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setTipoCambio(BigDecimal value) {
        this.tipoCambio = value;
    }

    /**
     * Gets the value of the total property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setTotal(BigDecimal value) {
        this.total = value;
    }

    /**
     * Gets the value of the tipoComprobante property.
     *
     * @return possible object is {@link CTipoDeComprobante }
     *
     */
    public String getTipoComprobante() {
        return tipoComprobante;
    }

    /**
     * Sets the value of the tipoComprobante property.
     *
     * @param value allowed object is {@link CTipoDeComprobante }
     *
     */
    public void setTipoComprobante(String value) {
        this.tipoComprobante = value;
    }

    /**
     * Gets the value of the metodoPago property.
     *
     * @return possible object is {@link CMetodoPago }
     *
     */
    public String getMetodoPago() {
        return metodoPago;
    }

    /**
     * Sets the value of the metodoPago property.
     *
     * @param value allowed object is {@link CMetodoPago }
     *
     */
    public void setMetodoPago(String value) {
        this.metodoPago = value;
    }

    /**
     * Gets the value of the lugarExpedicion property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLugarExpedicion() {
        return lugarExpedicion;
    }

    /**
     * Sets the value of the lugarExpedicion property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLugarExpedicion(String value) {
        this.lugarExpedicion = value;
    }

    /**
     * Gets the value of the confirmacion property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getConfirmacion() {
        return confirmacion;
    }

    /**
     * Sets the value of the confirmacion property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setConfirmacion(String value) {
        this.confirmacion = value;
    }
        
}


